"""Generate a tiny repeat-induction dataset for the NSA demo.

Each example is a random block ``base`` of length ``PERIOD`` repeated twice:

    seq = base ++ base

Predicting a token in the *second* copy requires attending back one whole period
(distance ``PERIOD``) to the matching token in the first copy — a long-range
dependency the local sliding window alone cannot cover. This is exactly what
NSA's selection branch is for, while the sliding window handles local structure
and compression gives cheap global context.

Run with:  python data/generate_data.py
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent


def make_example(period: int, num_symbols: int, rng: random.Random):
    base = [rng.randrange(num_symbols) for _ in range(period)]
    return base + base


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num-examples", type=int, default=64)
    parser.add_argument("--period", type=int, default=32)
    parser.add_argument("--num-symbols", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    examples = [make_example(args.period, args.num_symbols, rng) for _ in range(args.num_examples)]

    payload = {
        "task": "repeat_induction",
        "meta": {
            "period": args.period,
            "num_symbols": args.num_symbols,
            "vocab_size": args.num_symbols,
            "seq_len": 2 * args.period,
        },
        "examples": examples,
    }
    (DATA_DIR / "sequences.json").write_text(json.dumps(payload, indent=2))
    print(f"wrote {len(examples)} sequences (len={payload['meta']['seq_len']}) -> data/sequences.json")

    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `data/generate_data.py`. `sequences.json` holds repeat-"
        "induction sequences (`seq = base ++ base`); predicting a second-copy "
        "token requires attending back one period to the first copy. "
        "`demo/run_demo.py` also writes `nsa_run.json` with the NSA-vs-full "
        "comparison used by the visualization.\n"
    )
    print("wrote data/README.md")


if __name__ == "__main__":
    main()
