"""Clean "textbook" data vs larger "web-scraped" noisy data.

Phi-3's thesis (arXiv 2404.14219): with a small, *clean, structured* dataset a
small model can match — or beat — models trained on far more, messier data
("textbooks are all you need").  We make that concrete with a deterministic
**order-2 rule**:

    next_token = (prev1 + prev2) mod V

A sequence generated by iterating this rule is perfectly structured — like a
worked example in a textbook.  The **clean** dataset contains only such
sequences.

The **noisy** dataset is LARGER, but it contains *systematically wrong*
information: whenever the previous token falls in a "polluted" region, the next
token is consistently the WRONG value (rule + a fixed shift).  This mimics
unfiltered web data that repeats the same misinformation.  Crucially the error
is *consistent*, so — unlike high-entropy random noise, which averages out — no
amount of extra data can wash it away.  Both models are evaluated on the same
held-out CLEAN test set.
"""

from __future__ import annotations

import torch

VOCAB_SIZE = 20        # symbols 0..19; the rule is arithmetic mod VOCAB_SIZE
SEQ_LEN = 24           # tokens per sequence
_WRONG_SHIFT = 7       # systematic error added by the noisy corpus
_POLLUTED_BELOW = 8    # contexts with prev1 < this are systematically corrupted


def _rule_sequence(gen: torch.Generator) -> torch.Tensor:
    """One perfectly structured sequence: next = (prev1 + prev2) mod V."""
    seq = torch.empty(SEQ_LEN, dtype=torch.long)
    seq[0] = torch.randint(0, VOCAB_SIZE, (1,), generator=gen)
    seq[1] = torch.randint(0, VOCAB_SIZE, (1,), generator=gen)
    for i in range(2, SEQ_LEN):
        seq[i] = (seq[i - 1] + seq[i - 2]) % VOCAB_SIZE
    return seq


def make_clean_dataset(n: int, seed: int) -> torch.Tensor:
    """`n` perfectly rule-following sequences (the 'textbook')."""
    gen = torch.Generator().manual_seed(seed)
    return torch.stack([_rule_sequence(gen) for _ in range(n)])


def make_noisy_dataset(n: int, seed: int) -> torch.Tensor:
    """`n` sequences carrying a *consistent* systematic error.

    We start from clean rule sequences, then for every position whose true
    previous token is in the polluted region we overwrite the token with the
    WRONG (shifted) value.  About 40% of contexts are affected, and they are
    always wrong the same way — so the corpus flatly contradicts the true rule
    on those contexts.
    """
    gen = torch.Generator().manual_seed(seed)
    true = torch.stack([_rule_sequence(gen) for _ in range(n)])
    noisy = true.clone()
    for i in range(2, SEQ_LEN):
        prev1, prev2 = true[:, i - 1], true[:, i - 2]
        wrong = (prev1 + prev2 + _WRONG_SHIFT) % VOCAB_SIZE
        polluted = prev1 < _POLLUTED_BELOW
        noisy[:, i] = torch.where(polluted, wrong, true[:, i])
    return noisy


def rule_reconstruct(seq: list[int]) -> list[int]:
    """The pure-rule continuation from a sequence's first two tokens."""
    r = list(seq[:2])
    for i in range(2, len(seq)):
        r.append((r[-1] + r[-2]) % VOCAB_SIZE)
    return r


@torch.no_grad()
def next_token_accuracy(model, test: torch.Tensor) -> float:
    """Fraction of *rule-determined* positions predicted correctly.

    Only positions >= 2 are determined by the rule, so we score those.
    """
    model.eval()
    x, y = test[:, :-1], test[:, 1:]
    logits = model(x)
    pred = logits.argmax(-1)
    scored = pred[:, 1:]     # predictions for target positions t>=2
    gold = y[:, 1:]
    return (scored == gold).float().mean().item()
