"""Write the two demonstration datasets used by the LIMO demo to JSON.

Both datasets solve the same task (chained single-digit addition modulo 10) but
differ in the *quality* of the reasoning they demonstrate:

* ``curated_high_quality.json`` — a few hundred full step-by-step traces.
* ``bulk_low_quality.json``     — many terse answer-only "shortcut" traces.

The demo (``demo/run_demo.py``) builds these on the fly too; this script just
materializes them so you can open and inspect them.

Run with:  python data/generate_data.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import build_dataset  # noqa: E402

DATA_DIR = Path(__file__).resolve().parent


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num-terms", type=int, default=4)
    parser.add_argument("--curated", type=int, default=200)
    parser.add_argument("--bulk", type=int, default=2000)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    curated = build_dataset(args.curated, args.num_terms, "high", seed=args.seed + 1)
    bulk = build_dataset(args.bulk, args.num_terms, "low", seed=args.seed + 2)

    (DATA_DIR / "curated_high_quality.json").write_text(
        json.dumps({"quality": "high", "num_terms": args.num_terms, "examples": curated}, indent=2)
    )
    (DATA_DIR / "bulk_low_quality.json").write_text(
        json.dumps({"quality": "low", "num_terms": args.num_terms, "examples": bulk}, indent=2)
    )
    print(f"wrote {len(curated)} curated high-quality traces -> data/curated_high_quality.json")
    print(f"wrote {len(bulk)} bulk low-quality traces -> data/bulk_low_quality.json")

    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `data/generate_data.py`. Two datasets for the same task "
        "(chained single-digit addition modulo 10):\n\n"
        "- `curated_high_quality.json`: a few hundred **step-by-step** traces "
        "(`3+5+2+4=3+5=8;8+2=0;0+4=4#4`).\n"
        "- `bulk_low_quality.json`: many **answer-only** shortcuts "
        "(`3+5+2+4=#4`).\n\n"
        "Both have correct answers; only the demonstrated reasoning quality "
        "differs. `demo/run_demo.py` also writes `limo_run.json` with results.\n"
    )
    print("wrote data/README.md")


if __name__ == "__main__":
    main()
