"""Generate small, human-readable demo datasets for the Transformer demos.

The goal is not to reproduce a full machine-translation corpus, but to give
you concrete, inspectable data so you can *experience the structure* of the
paper: fixed-vocabulary token sequences that flow through the encoder,
decoder and attention exactly as described in "Attention Is All You Need".

Two toy sequence-to-sequence tasks are produced, both over a tiny integer
vocabulary:

* ``copy``    - the target is identical to the source.
* ``reverse`` - the target is the source read backwards.

Special token ids are shared with the training demo::

    0 = PAD,  1 = BOS (begin),  2 = EOS (end)

Content tokens use ids >= 3. Everything is written to ``data/`` as JSON so it
can be opened in any editor.

Run with:  python demo/generate_demo_data.py
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

PAD, BOS, EOS = 0, 1, 2
NUM_SPECIAL = 3

DATA_DIR = Path(__file__).resolve().parent.parent / "data"


def make_examples(task: str, n: int, seq_len: int, vocab_size: int, rng: random.Random):
    examples = []
    for _ in range(n):
        content = [rng.randrange(NUM_SPECIAL, vocab_size) for _ in range(seq_len)]
        if task == "copy":
            target = list(content)
        elif task == "reverse":
            target = list(reversed(content))
        else:  # pragma: no cover - guarded by argparse choices
            raise ValueError(f"unknown task: {task}")
        examples.append(
            {
                "source": content,
                "target_in": [BOS] + target,
                "target_out": target + [EOS],
            }
        )
    return examples


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num-examples", type=int, default=64)
    parser.add_argument("--seq-len", type=int, default=8)
    parser.add_argument("--vocab-size", type=int, default=16)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    meta = {
        "special_tokens": {"PAD": PAD, "BOS": BOS, "EOS": EOS},
        "vocab_size": args.vocab_size,
        "seq_len": args.seq_len,
        "content_token_range": [NUM_SPECIAL, args.vocab_size - 1],
    }

    for task in ("copy", "reverse"):
        examples = make_examples(
            task, args.num_examples, args.seq_len, args.vocab_size, rng
        )
        payload = {"task": task, "meta": meta, "examples": examples}
        out_path = DATA_DIR / f"{task}_dataset.json"
        out_path.write_text(json.dumps(payload, indent=2))
        print(f"wrote {len(examples):>3} '{task}' examples -> {out_path}")

    # A short, friendly explanation of the on-disk format.
    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `demo/generate_demo_data.py`. Each `*_dataset.json` file "
        "contains toy sequence-to-sequence examples over a tiny integer "
        "vocabulary.\n\n"
        "Special token ids: `0 = PAD`, `1 = BOS`, `2 = EOS`; content tokens use "
        "ids `>= 3`.\n\n"
        "Each example has:\n\n"
        "- `source`: the encoder input sequence.\n"
        "- `target_in`: the decoder input (`BOS` + target), used for teacher "
        "forcing.\n"
        "- `target_out`: the expected next tokens (target + `EOS`).\n\n"
        "Tasks: `copy` (target == source) and `reverse` (target == reversed "
        "source).\n"
    )
    print(f"wrote data/README.md")


if __name__ == "__main__":
    main()
