"""Write the toy reasoning problem set used by the Kimi k1.5 demo to JSON.

The task is deterministic and tiny: every pair of digits ``(a, b)`` with the
target ``max(a, b)``. There is no train/test split — RL learns directly from the
reward on this problem distribution. This script just materializes the set so
you can inspect it; the demo builds it on the fly too.

Run with:  python data/generate_data.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import answer_of, prompt_of  # noqa: E402

DATA_DIR = Path(__file__).resolve().parent
NUM_VALUES = 10


def main() -> None:
    problems = [
        {"a": a, "b": b, "prompt": prompt_of(a, b), "answer": answer_of(a, b)}
        for a in range(NUM_VALUES)
        for b in range(NUM_VALUES)
    ]
    (DATA_DIR / "problems.json").write_text(
        json.dumps({"task": "max(a,b)", "num_values": NUM_VALUES, "problems": problems}, indent=2)
    )
    print(f"wrote {len(problems)} problems -> data/problems.json")

    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `data/generate_data.py`. `problems.json` lists every "
        "`(a, b)` pair with target `max(a, b)` — the toy reasoning task the RL "
        "policy is trained on. `demo/run_demo.py` also writes `kimi_run.json` "
        "with the RL learning curves (accuracy and mean chain length).\n"
    )
    print("wrote data/README.md")


if __name__ == "__main__":
    main()
