"""Generate a tiny structured dataset for the LLaDA masked-diffusion demo.

The "language" is deliberately simple so that *validity* is easy to check by
eye and in code: every sequence is **periodic with period P**. A random motif
of ``P`` tokens is tiled to fill the sequence:

    motif = [t0, t1, ..., t(P-1)]      seq = motif repeated

This imposes a hard *global* constraint — every position ``i`` must equal
position ``i + P`` — which a non-autoregressive generator has to satisfy
across the whole sequence at once. That is exactly the kind of long-range
consistency the bidirectional mask predictor must learn to fill in and to
generate from scratch.

Run with:  python data/generate_data.py
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent


def make_sequence(seq_len: int, period: int, vocab: int, rng: random.Random):
    motif = [rng.randrange(vocab) for _ in range(period)]
    return [motif[i % period] for i in range(seq_len)]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num-examples", type=int, default=64)
    parser.add_argument("--seq-len", type=int, default=12)
    parser.add_argument("--period", type=int, default=3)
    parser.add_argument("--vocab", type=int, default=10, help="content vocab size V")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    seqs = [
        make_sequence(args.seq_len, args.period, args.vocab, rng)
        for _ in range(args.num_examples)
    ]

    payload = {
        "task": "periodic_sequences",
        "meta": {
            "vocab": args.vocab,          # content tokens 0..V-1
            "mask_id": args.vocab,        # [MASK] is the last id
            "vocab_size": args.vocab + 1,
            "seq_len": args.seq_len,
            "period": args.period,
            "rule": "seq[i] == seq[i + P] (period-P repetition)",
        },
        "examples": seqs,
    }
    out = DATA_DIR / "sequences.json"
    out.write_text(json.dumps(payload, indent=2))
    print(f"wrote {len(seqs)} period-{args.period} sequences -> {out}")

    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `data/generate_data.py`. `sequences.json` holds toy "
        "structured sequences that are **periodic with period P**: a random "
        "motif of `P` tokens is tiled across the sequence, so `seq[i] == "
        "seq[i + P]`.\n\n"
        "Content tokens use ids `0..V-1`; the reserved `[MASK]` token is id `V`.\n"
    )
    print("wrote data/README.md")


if __name__ == "__main__":
    main()
