"""Generate a tiny sample of the multi-step arithmetic task in all three styles.

Each problem is a chained single-digit addition mod 10; we render it as Standard
(direct answer), Chain of Thought (verbose), and Chain of Draft (terse). This
file is illustrative — ``demo/run_demo.py`` generates its own training data and
also writes ``cod_run.json`` with the accuracy/token comparison.

Run with:  python data/generate_data.py
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(DATA_DIR.parent))

from src.task import STYLES, STYLE_NAME, make_problem, prompt_of, RENDER  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--num-examples", type=int, default=12)
    parser.add_argument("--num-terms", type=int, default=4)
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    rng = random.Random(args.seed)
    examples = []
    for _ in range(args.num_examples):
        terms, ans = make_problem(args.num_terms, rng)
        styles = {}
        for s in STYLES:
            completion = RENDER[s](terms)
            styles[s] = {
                "name": STYLE_NAME[s],
                "prompt": prompt_of(s, terms),
                "completion": completion,
                "tokens": len(completion),
            }
        examples.append({"terms": terms, "answer": ans, "styles": styles})

    payload = {"task": "chained_add_mod10", "num_terms": args.num_terms, "examples": examples}
    (DATA_DIR / "examples.json").write_text(json.dumps(payload, indent=2))
    print(f"wrote {len(examples)} examples (num_terms={args.num_terms}) -> data/examples.json")

    (DATA_DIR / "README.md").write_text(
        "# Demo data\n\n"
        "Generated by `data/generate_data.py`. `examples.json` shows the same "
        "problems rendered in three styles (Standard / CoT / CoD) with token "
        "counts. `demo/run_demo.py` also writes `cod_run.json` with the "
        "accuracy-vs-tokens comparison used by the visualization.\n"
    )
    print("wrote data/README.md")


if __name__ == "__main__":
    main()
